package mx.com.underrito.metro.free.constant;

public class MetroConstant {
	
	public static final int NONE = 0;
	public static final int DRAG = 1;
	public static final int ZOOM = 2;
	public static final int END_DRAG = 3;
	public static final int INCLINADO_45 = 4;
	public static final int INCLINADO_135 = 5;
	public static final int INCLINADO_225 = 6;
	public static final int INCLINADO_315 = 7;
	public static final int VERTICAL_IZQUIERDO = 3;
	public static final int VERTICAL_DERECHO = 2;
	public static final int HORIZONTAL_ARRIBA = 1;
	public static final int HORIZONTAL_ABAJO = 0;
	public static final float ESCALA_MINIMA=1f;
	public static final float ESCALA_MAXIMA=5f;
	public static final float MOVER_MAXIMO=0.7f;
	public static final String ESTACION_COLOR="#000000";
	public static final String ESTACION_SEL_COLOR="#000000";
	public static final String SEGMENTO_COLOR="#000000";
	public static final String SEGMENTO_SEL_COLOR="#66FF00";
	public static final float ESTACION_TEXTO_PADDING=10;
	public static final String ESTACION_TEXTO_COLOR="#000000";
	public static final String ESTACION_TEXTO_SEL_COLOR="#000000";
	public static final String ESTACION_TRAZA_COLOR="#66FF00";
	public static final String RUTA_PARAM="ruta";
	public static final String ESTACION_TRAZA="estacionTraza";
	public static final String SEGMENTO_PARAM="listaSegmento";
	public static final String LINEA_PARAM="linea";
	public static final String PREFS_METRO = "UnderMetro";
	public static final String CAPANIA ="a14f31229ed5573";
	public static final boolean ADMOB_MODE	=	true;
	public static final String DEVICE_DEV ="73B9986EE0BC5C8750DE411704CFB08F";
	public static final String PREFERENCIA_LINEA12		= "preferenciaLinea12";
	public static final String PREFERENCIA_BOTONZOOM	= "preferenciaBotonZoom";
	public static final String BASE64_PUBLIC_KEY 		= "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqRrOkg+KTX/Xb4ePbYTfEPJ41hI9W1RfMlkmjB4qj0N2/qlY9HSDliSSfFvfjB4o1ehZzfsQx4DYR+XBhIi7+j1gVDbCzaqyYNDQmM1r5ZV7Hrw4IZ3UhPoRGm2uJnI0B0Wi1ItVskaYwjP/H+m6CuWDsjcHRpBmVYUdmKULe/WXrkKR70UEMwkoMgz/II744s5C8AcCQOAH8Kl4BMIPhk0f3WReFeXI0TzvdGkESWxOMZc5ZduuakBs5QroLjvG3P18kqOyzR0Co1kBIGP1AqifJVblgco4Kf/y3KRkuzSS3xx2UK2TWnn7P/kwVJ2N85LhZmZsV4szuUJ1VlR8HQIDAQAB"; //truncated for this example
    public static final int VOTAR_DIAS=7;
    public static final int VOTAR_VECES=10;
    public static final int PESO_TRANSBORDE=5000; 
    public static final int ESTACION_PASO=0;
    public static final int ESTACION_TRANSBORDE=1;

    

    public static final String VOTAR_ACTIVO="metrovotaractivopref";
    public static final String VOTAR_INICIO="metrovotarinicio";
    public static final String VOTAR_CONTADOR="metrovotarcontador";


	public static final byte[] SALT = new byte[] {
        -13, 5, 30, -29, -13, -57, 74, -64, 51, 88, -18,
        -18, 13, -5, -36, -113, -29, 32, -64, 89
        };


	public static final int OBSERVATORIO_ID=0;	public static final String OBSERVATORIO_NAME="Observatorio";
	public static final int TACUBAYA_ID=1;	public static final String TACUBAYA_NAME="Tacubaya";
	public static final int JUANACATLAN_ID=2;	public static final String JUANACATLAN_NAME="Juanacatlan";
	public static final int CHAPULTEPEC_ID=3;	public static final String CHAPULTEPEC_NAME="Chapultepec";
	public static final int SEVILLA_ID=4;	public static final String SEVILLA_NAME="Sevilla";
	public static final int INSURGENTES_ID=5;	public static final String INSURGENTES_NAME="Insurgentes";
	public static final int CUAUHTEMOC_ID=6;	public static final String CUAUHTEMOC_NAME="Cuauhtemoc";
	public static final int BALDERAS_ID=7;	public static final String BALDERAS_NAME="Balderas";
	public static final int SALTO_DEL_AGUA_ID=8;	public static final String SALTO_DEL_AGUA_NAME="Salto del Agua";
	public static final int ISABEL_LA_CATOLICA_ID=9;	public static final String ISABEL_LA_CATOLICA_NAME="Isabel la Catolica";
	public static final int PINO_SUAREZ_ID=10;	public static final String PINO_SUAREZ_NAME="Pino Suarez";
	public static final int MERCED_ID=11;	public static final String MERCED_NAME="Merced";
	public static final int CANDELARIA_ID=12;	public static final String CANDELARIA_NAME="Candelaria";
	public static final int SAN_LAZARO_ID=13;	public static final String SAN_LAZARO_NAME="San Lazaro";
	public static final int MOCTEZUMA_ID=14;	public static final String MOCTEZUMA_NAME="Moctezuma";
	public static final int BALBUENA_ID=15;	public static final String BALBUENA_NAME="Balbuena";
	public static final int BOULEVARD_PUERTO_AEREO_ID=16;	public static final String BOULEVARD_PUERTO_AEREO_NAME="Boulevard Puerto Aereo";
	public static final int GOMEZ_FARIAS_ID=17;	public static final String GOMEZ_FARIAS_NAME="Gomez Farias";
	public static final int ZARAGOZA_ID=18;	public static final String ZARAGOZA_NAME="Zaragoza";
	public static final int PANTITLAN_ID=19;	public static final String PANTITLAN_NAME="Pantitlan";
	public static final int CUATRO_CAMINOS_ID=20;	public static final String CUATRO_CAMINOS_NAME="Cuatro Caminos";
	public static final int PANTEONES_ID=21;	public static final String PANTEONES_NAME="Panteones";
	public static final int TACUBA_ID=22;	public static final String TACUBA_NAME="Tacuba";
	public static final int CUITLAHUAC_ID=23;	public static final String CUITLAHUAC_NAME="Cuitlahuac";
	public static final int POPOTLA_ID=24;	public static final String POPOTLA_NAME="Popotla";
	public static final int COLEGIO_MILITAR_ID=25;	public static final String COLEGIO_MILITAR_NAME="Colegio Militar";
	public static final int NORMAL_ID=26;	public static final String NORMAL_NAME="Normal";
	public static final int SAN_COSME_ID=27;	public static final String SAN_COSME_NAME="San Cosme";
	public static final int REVOLUCION_ID=28;	public static final String REVOLUCION_NAME="Revolucion";
	public static final int HIDALGO_ID=29;	public static final String HIDALGO_NAME="Hidalgo";
	public static final int BELLAS_ARTES_ID=30;	public static final String BELLAS_ARTES_NAME="Bellas Artes";
	public static final int ALLENDE_ID=31;	public static final String ALLENDE_NAME="Allende";
	public static final int ZOCALO_ID=32;	public static final String ZOCALO_NAME="Zocalo";
	public static final int SAN_ANTONIO_ABAD_ID=33;	public static final String SAN_ANTONIO_ABAD_NAME="San Antonio Abad";
	public static final int CHABACANO_ID=34;	public static final String CHABACANO_NAME="Chabacano";
	public static final int VIADUCTO_ID=35;	public static final String VIADUCTO_NAME="Viaducto";
	public static final int XOLA_ID=36;	public static final String XOLA_NAME="Xola";
	public static final int VILLA_DE_CORTES_ID=37;	public static final String VILLA_DE_CORTES_NAME="Villa de Cortes";
	public static final int NATIVITAS_ID=38;	public static final String NATIVITAS_NAME="Nativitas";
	public static final int PORTALES_ID=39;	public static final String PORTALES_NAME="Portales";
	public static final int ERMITA_ID=40;	public static final String ERMITA_NAME="Ermita";
	public static final int GENERAL_ANAYA_ID=41;	public static final String GENERAL_ANAYA_NAME="General Anaya";
	public static final int TASQUENA_ID=42;	public static final String TASQUENA_NAME="Tasqueña";
	public static final int INDIOS_VERDES_ID=43;	public static final String INDIOS_VERDES_NAME="Indios Verdes";
	public static final int DEPORTIVO_18_DE_MARZO_ID=44;	public static final String DEPORTIVO_18_DE_MARZO_NAME="Deportivo 18 de Marzo";
	public static final int POTRERO_ID=45;	public static final String POTRERO_NAME="Potrero";
	public static final int LA_RAZA_ID=46;	public static final String LA_RAZA_NAME="La Raza";
	public static final int TLATELOLCO_ID=47;	public static final String TLATELOLCO_NAME="Tlatelolco";
	public static final int GUERRERO_ID=48;	public static final String GUERRERO_NAME="Guerrero";
	public static final int JUAREZ_ID=49;	public static final String JUAREZ_NAME="Juarez";
	public static final int NINOS_HEROES_ID=50;	public static final String NINOS_HEROES_NAME="Niños Heroes";
	public static final int HOSPITAL_GENERAL_ID=51;	public static final String HOSPITAL_GENERAL_NAME="Hospital General";
	public static final int CENTRO_MEDICO_ID=52;	public static final String CENTRO_MEDICO_NAME="Centro Medico";
	public static final int ETIOPIA_PLAZA_DE_LA_TRANSPARENCIA_ID=53;	public static final String ETIOPIA_PLAZA_DE_LA_TRANSPARENCIA_NAME="Etiopia / Plaza de la Transparencia";
	public static final int EUGENIA_ID=54;	public static final String EUGENIA_NAME="Eugenia";
	public static final int DIVISION_DEL_NORTE_ID=55;	public static final String DIVISION_DEL_NORTE_NAME="Division del Norte";
	public static final int ZAPATA_ID=56;	public static final String ZAPATA_NAME="Zapata";
	public static final int COYOACAN_ID=57;	public static final String COYOACAN_NAME="Coyoacan";
	public static final int VIVEROS_DERECHOS_HUMANOS_ID=58;	public static final String VIVEROS_DERECHOS_HUMANOS_NAME="Viveros / Derechos Humanos";
	public static final int MIGUEL_ANGEL_DE_QUEVEDO_ID=59;	public static final String MIGUEL_ANGEL_DE_QUEVEDO_NAME="Miguel Angel de Quevedo";
	public static final int COPILCO_ID=60;	public static final String COPILCO_NAME="Copilco";
	public static final int UNIVERSIDAD_ID=61;	public static final String UNIVERSIDAD_NAME="Universidad";
	public static final int MARTIN_CARRERA_ID=62;	public static final String MARTIN_CARRERA_NAME="Martin Carrera";
	public static final int TALISMAN_ID=63;	public static final String TALISMAN_NAME="Talisman";
	public static final int BONDOJITO_ID=64;	public static final String BONDOJITO_NAME="Bondojito";
	public static final int CONSULADO_ID=65;	public static final String CONSULADO_NAME="Consulado";
	public static final int CANAL_DEL_NORTE_ID=66;	public static final String CANAL_DEL_NORTE_NAME="Canal del Norte";
	public static final int MORELOS_ID=67;	public static final String MORELOS_NAME="Morelos";
	public static final int FRAY_SERVANDO_ID=68;	public static final String FRAY_SERVANDO_NAME="Fray Servando";
	public static final int JAMAICA_ID=69;	public static final String JAMAICA_NAME="Jamaica";
	public static final int SANTA_ANITA_ID=70;	public static final String SANTA_ANITA_NAME="Santa Anita";
	public static final int HANGARES_ID=71;	public static final String HANGARES_NAME="Hangares";
	public static final int TERMINAL_AEREA_ID=72;	public static final String TERMINAL_AEREA_NAME="Terminal Aerea";
	public static final int OCEANIA_ID=73;	public static final String OCEANIA_NAME="Oceania";
	public static final int ARAGON_ID=74;	public static final String ARAGON_NAME="Aragon";
	public static final int EDUARDO_MOLINA_ID=75;	public static final String EDUARDO_MOLINA_NAME="Eduardo Molina";
	public static final int VALLE_GOMEZ_ID=76;	public static final String VALLE_GOMEZ_NAME="Valle Gomez";
	public static final int MISTERIOS_ID=77;	public static final String MISTERIOS_NAME="Misterios";
	public static final int AUTOBUSES_DEL_NORTE_ID=78;	public static final String AUTOBUSES_DEL_NORTE_NAME="Autobuses del Norte";
	public static final int INSTITUTO_DEL_PETROLEO_ID=79;	public static final String INSTITUTO_DEL_PETROLEO_NAME="Instituto del Petroleo";
	public static final int POLITECNICO_ID=80;	public static final String POLITECNICO_NAME="Politecnico";
	public static final int EL_ROSARIO_ID=81;	public static final String EL_ROSARIO_NAME="El Rosario";
	public static final int TEZOZOMOC_ID=82;	public static final String TEZOZOMOC_NAME="Tezozomoc";
	public static final int AZCAPOTZALCO_ID=83;	public static final String AZCAPOTZALCO_NAME="Azcapotzalco";
	public static final int FERRERIA_ID=84;	public static final String FERRERIA_NAME="Ferreria";
	public static final int NORTE_45_ID=85;	public static final String NORTE_45_NAME="Norte 45";
	public static final int VALLEJO_ID=86;	public static final String VALLEJO_NAME="Vallejo";
	public static final int LINDAVISTA_ID=87;	public static final String LINDAVISTA_NAME="Lindavista";
	public static final int LA_VILLA_BASILICA_ID=88;	public static final String LA_VILLA_BASILICA_NAME="La Villa-Basilica";
	public static final int AQUILES_SEDAN_ID=89;	public static final String AQUILES_SEDAN_NAME="Aquiles Sedan";
	public static final int CAMARONES_ID=90;	public static final String CAMARONES_NAME="Camarones";
	public static final int REFINERIA_ID=91;	public static final String REFINERIA_NAME="Refineria";
	public static final int SAN_JOAQUIN_ID=92;	public static final String SAN_JOAQUIN_NAME="San Joaquin";
	public static final int POLANCO_ID=93;	public static final String POLANCO_NAME="Polanco";
	public static final int AUDITORIO_ID=94;	public static final String AUDITORIO_NAME="Auditorio";
	public static final int CONSTITUYENTES_ID=95;	public static final String CONSTITUYENTES_NAME="Constituyentes";
	public static final int SAN_PEDRO_DE_LOS_PINOS_ID=96;	public static final String SAN_PEDRO_DE_LOS_PINOS_NAME="San Pedro de los Pinos";
	public static final int SAN_ANTONIO_ID=97;	public static final String SAN_ANTONIO_NAME="San Antonio";
	public static final int MIXCOAC_ID=98;	public static final String MIXCOAC_NAME="Mixcoac";
	public static final int BARRANCA_DEL_MUERTO_ID=99;	public static final String BARRANCA_DEL_MUERTO_NAME="Barranca del Muerto";
	public static final int GARIBALDI_ID=100;	public static final String GARIBALDI_NAME="Garibaldi";
	public static final int SAN_JUAN_DE_LETRAN_ID=101;	public static final String SAN_JUAN_DE_LETRAN_NAME="San Juan de Letran";
	public static final int DOCTORES_ID=102;	public static final String DOCTORES_NAME="Doctores";
	public static final int OBRERA_ID=103;	public static final String OBRERA_NAME="Obrera";
	public static final int LA_VIGA_ID=104;	public static final String LA_VIGA_NAME="La Viga";
	public static final int COYUYA_ID=105;	public static final String COYUYA_NAME="Coyuya";
	public static final int IZTACALCO_ID=106;	public static final String IZTACALCO_NAME="Iztacalco";
	public static final int APATLACO_ID=107;	public static final String APATLACO_NAME="Apatlaco";
	public static final int ACULCO_ID=108;	public static final String ACULCO_NAME="Aculco";
	public static final int ESCUADRON_201_ID=109;	public static final String ESCUADRON_201_NAME="Escuadron 201";
	public static final int ATLALILCO_ID=110;	public static final String ATLALILCO_NAME="Atlalilco";
	public static final int IZTAPALAPA_ID=111;	public static final String IZTAPALAPA_NAME="Iztapalapa";
	public static final int CERRO_DE_LA_ESTRELLA_ID=112;	public static final String CERRO_DE_LA_ESTRELLA_NAME="Cerro de la Estrella";
	public static final int UAM_I_ID=113;	public static final String UAM_I_NAME="UAM-I";
	public static final int CONSTITUCION_DE_1917_ID=114;	public static final String CONSTITUCION_DE_1917_NAME="Constitucion de 1917";
	public static final int PATRIOTISMO_ID=115;	public static final String PATRIOTISMO_NAME="Patriotismo";
	public static final int CHILPANCINGO_ID=116;	public static final String CHILPANCINGO_NAME="Chilpancingo";
	public static final int LAZARO_CARDENAS_ID=117;	public static final String LAZARO_CARDENAS_NAME="Lazaro Cardenas";
	public static final int MIXIUHCA_ID=118;	public static final String MIXIUHCA_NAME="Mixiuhca";
	public static final int VELODROMO_ID=119;	public static final String VELODROMO_NAME="Velodromo";
	public static final int CIUDAD_DEPORTIVA_ID=120;	public static final String CIUDAD_DEPORTIVA_NAME="Ciudad Deportiva";
	public static final int PUEBLA_ID=121;	public static final String PUEBLA_NAME="Puebla";
	public static final int AGRICOLA_ORIENTAL_ID=122;	public static final String AGRICOLA_ORIENTAL_NAME="Agricola Oriental";
	public static final int CANAL_DE_SAN_JUAN_ID=123;	public static final String CANAL_DE_SAN_JUAN_NAME="Canal de San Juan";
	public static final int TEPALCATES_ID=124;	public static final String TEPALCATES_NAME="Tepalcates";
	public static final int GUELATAO_ID=125;	public static final String GUELATAO_NAME="Guelatao";
	public static final int PENON_VIEJO_ID=126;	public static final String PENON_VIEJO_NAME="Peñon Viejo";
	public static final int ACATITLA_ID=127;	public static final String ACATITLA_NAME="Acatitla";
	public static final int SANTA_MARTA_ID=128;	public static final String SANTA_MARTA_NAME="Santa Marta";
	public static final int LOS_REYES_ID=129;	public static final String LOS_REYES_NAME="Los Reyes";
	public static final int LA_PAZ_ID=130;	public static final String LA_PAZ_NAME="La Paz";
	public static final int CIUDAD_AZTECA_ID=131;	public static final String CIUDAD_AZTECA_NAME="Ciudad Azteca";
	public static final int PLAZA_ARAGON_ID=132;	public static final String PLAZA_ARAGON_NAME="Plaza Aragon";
	public static final int OLIMPICA_ID=133;	public static final String OLIMPICA_NAME="Olimpica";
	public static final int ECATEPEC_ID=134;	public static final String ECATEPEC_NAME="Ecatepec";
	public static final int MUZQUIZ_ID=135;	public static final String MUZQUIZ_NAME="Muzquiz";
	public static final int RIO_DE_LOS_REMEDIOS_ID=136;	public static final String RIO_DE_LOS_REMEDIOS_NAME="Rio de los Remedios";
	public static final int IMPULSORA_ID=137;	public static final String IMPULSORA_NAME="Impulsora";
	public static final int NEZAHUALCOYOTL_ID=138;	public static final String NEZAHUALCOYOTL_NAME="Nezahualcoyotl";
	public static final int VILLA_DE_ARAGON_ID=139;	public static final String VILLA_DE_ARAGON_NAME="Villa de Aragon";
	public static final int BOSQUE_DE_ARAGON_ID=140;	public static final String BOSQUE_DE_ARAGON_NAME="Bosque de Aragon";
	public static final int DEPORTIVO_OCEANIA_ID=141;	public static final String DEPORTIVO_OCEANIA_NAME="Deportivo Oceania";
	public static final int ROMERO_RUBIO_ID=142;	public static final String ROMERO_RUBIO_NAME="Romero Rubio";
	public static final int R_FLORES_MAGON_ID=143;	public static final String R_FLORES_MAGON_NAME="R. Flores Magon";
	public static final int TEPITO_ID=144;	public static final String TEPITO_NAME="Tepito";
	public static final int LAGUNILLA_ID=145;	public static final String LAGUNILLA_NAME="Lagunilla";
	public static final int BUENAVISTA_ID=146;	public static final String BUENAVISTA_NAME="Buenavista";
	
	public static final int TLAHUAC_ID=147;	public static final String TLAHUAC_NAME="Tlahuac";
	public static final int TLALTENCO_ID=148;	public static final String TLALTENCO_NAME="Tlaltenco";
	public static final int ZAPOTITLAN_ID=149;	public static final String ZAPOTITLAN_NAME="Zapotitlan";
	public static final int NOPALERA_ID=150;	public static final String NOPALERA_NAME="Nopalera";
	public static final int OLIVOS_ID=151;	public static final String OLIVOS_NAME="Olivos";
	public static final int TEZONCO_ID=152;	public static final String TEZONCO_NAME="Tezonco";
	public static final int PERIFERICO_ORIENTE_ID=153;	public static final String PERIFERICO_ORIENTE_NAME="Periferico Oriente";
	public static final int CALLE_11_ID=154;	public static final String CALLE_11_NAME="Calle 11";
	public static final int LOMAS_ESTRELLA_ID=155;	public static final String LOMAS_ESTRELLA_NAME="Lomas Estrella";
	public static final int SAN_ANDRES_TOMATLAN_ID=156;	public static final String SAN_ANDRES_TOMATLAN_NAME="San Andres Tomatlan";
	public static final int CULHUACAN_ID=157;	public static final String CULHUACAN_NAME="Culhuacan";
	public static final int MEXICALTZINGO_ID=158;	public static final String MEXICALTZINGO_NAME="Mexicaltzingo";
	public static final int EJE_CENTRAL_ID=159;	public static final String EJE_CENTRAL_NAME="Eje Central";
	public static final int PARQUE_DE_LOS_VENADOS_ID=160;	public static final String PARQUE_DE_LOS_VENADOS_NAME="Parque de los venados";
	public static final int HOSPITAL_20_DE_NOVIEMBRE_ID=161;	public static final String HOSPITAL_20_DE_NOVIEMBRE_NAME="20 de Noviembre";
	public static final int INSURGENTES_SUR_ID=162;	public static final String INSURGENTES_SUR_NAME="Insurgentes Sur";

	
}
